export { addSupertokensConfigFile } from "./addSupertokensConfigFile";
export { replaceLoginPage } from "./replaceLoginPage";
export { replaceTypesModule } from "./replaceTypesModule";
export { replaceDataProviderModule } from "./replaceDataProviderModule";
export { addSupertokensAuthProvider } from "./addSupertokensAuthProvider";
export { removeNonSupertokensAuthProviderImportsFromAppModule } from "./removeNonSupertokensAuthProviderImportsFromAppModule";
export { removeNonSupertokensAuthProviderModules } from "./removeNonSupertokensAuthProviderModules";
export { addConsumeMagicLinkModule } from "./addConsumeMagicLinkModule";
export { addAuthCallbackModule } from "./addAuthCallbackModule";
export { removeUnneededAdminUIFiles } from "./removeUnneededFiles"
