export { alterGraphqlSettingsInAppModule } from "./alterGraphqlSettings";
export { addRemoveAuthFiles } from "./addRemoveAuthFiles";
export { createSupertokensService } from "./createSupertokensService";
export { removeRemoveDefaultCorsSettingInMain } from "./removeRemoveDefaultCorsSettingInMain";
export { addSupertokensIdFieldToAuthEntity } from "./addSupertokensIdFieldToAuthEntity";
export { addAuthModuleInAuthDir } from "./addAuthModuleInAuthDir";
export { makeSTIdFieldOptionalInCreation } from "./makeSTIdFieldOptionalInCreation";
export { removeSTIdFromUpdateInput } from "./removeSTIdFromUpdateInput";
export { injectAuthService } from "./injectAuthService";
export { createAuthService } from "./createAuthService";
export { verifyAuthCorePluginIsInstalled } from "./verifyAuthCorePluginIsInstalled";
export { verifyEmailAndPasswordFieldsExist } from "./verifyEmailAndPasswordFieldsExist";
export { alterAuthControllerBaseMethods, alterAuthResolverBaseMethods } from "./alterAuthControllerResolverMethods";
export { removeEmailUsernamePasswordField } from "./removeEmailUsernamePasswordField";
export { addEmailPropertyToDTO, addPhoneNumberPropertyToDTO, addThirdPartyIdPropertyToDTO } from "./addPropertyToDTO";
export { alterSeedData } from "./alterSeedData";
export { replaceCustomSeedTemplate } from "./replaceCustomSeedTemplate";
export { alterSeedCode } from "./alterSeedCode";
