export { alterGraphqlSettingsInAppModule } from "./alterGraphqlSettings";
export { addSupertokensFiles, createSupertokensService } from "./addSupertokensFiles";
export { removeRemoveDefaultCorsSettingInMain } from "./removeRemoveDefaultCorsSettingInMain";
export { addSupertokensIdFieldToAuthEntity } from "./addSupertokensIdFieldToAuthEntity";
export { addAuthModuleInAuthDir } from "./addAuthModuleInAuthDir";
export { makeSTIdFieldOptionalInCreation } from "./makeSTIdFieldOptionalInCreation";
export { removeSTIdFromUpdateInput } from "./removeSTIdFromUpdateInput";
export { injectAuthService } from "./injectAuthService";
export { createAuthService } from "./createAuthService";
export { verifyAuthCorePluginIsInstalled } from "./verifyAuthCorePluginIsInstalled";
export { verifyEmailAndPasswordFieldsExist } from "./verifyEmailAndPasswordFieldsExist";
export { alterAuthControllerBaseMethods, alterAuthResolverBaseMethods } from "./alterAuthControllerResolverMethods";
