export const metadataNameKey = "${{ METADATA_NAME }}";
export const metadataDescriptionKey = "${{ METADATA_DESCRIPTION }}";

export const metadataLabelsKey = "${{ METADATA_LABELS }}";
export const metadataAnnotationsKey = "${{ METADATA_ANNOTATIONS }}";
export const metadataTagsKey = "${{ METADATA_TAGS }}";

export const specTypeKey = "${{ SPEC_TYPE }}";
export const specLifecycleKey = "${{ SPEC_LIFECYCLE }}";
export const specOwnerKey = "${{ SPEC_OWNER }}";

export const workspaceIdKey = "${{ WORKSPACE_ID }}";
export const projectIdKey = "${{ PROJECT_ID }}";
export const serviceIdKey = "${{ SERVICE_ID }}";

export const defaultNamePrefix = "Amplication";
export const defaultDescription =
  "Backend service which is auto-generated by Amplication.";
export const defaultLabels = new Map([["vendor", "amplication"]]);
export const defaultAnnotations = new Map([["vendor", "amplication"]]);
export const defaultTags = ["Node.js"];
export const defaultLifecycle = "production";
export const defaultOwner = "development";
